version: '3'  # Version of Docker Compose file format

services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db  # Depend on the database service
    environment:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/news  # Set the PostgreSQL database URL for the FastAPI app
    restart: always

  db: # Service for the PostgreSQL database
    image: postgres:latest  # Use the latest PostgreSQL Docker image from Docker Hub
    ports:
      - "5432:5432"  # Map port 5432 of the host to port 5432 of the container
    environment:
      POSTGRES_USER: postgres  # Set the PostgreSQL username
      POSTGRES_PASSWORD: postgres  # Set the PostgreSQL password
      POSTGRES_DB: news  # Set the name of the PostgreSQL database
    volumes:
      - pgdata:/var/lib/postgresql/data  # Mount volume for persistent data storage
    restart: always  # Always restart the container if it stops

volumes: # Define named volumes to be used by services
  pgdata:  # Volume for PostgreSQL data storage
